services:
  db:
    image: postgres:15-alpine
    env_file:
      - ./Backend/.env
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
  pagos:
    build:
      context: ./Backend
      dockerfile: Dockerfile
      args:
        APP_NAME: pagos
    env_file:
      - ./Backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - db

  conciliacion:
    build:
      context: ./Backend
      dockerfile: Dockerfile
      args:
        APP_NAME: conciliacion
    env_file:
      - ./Backend/.env
    ports:
      - "3002:3002"
    depends_on:
      - db

  analitica:
    build:
      context: ./Backend
      dockerfile: Dockerfile
      args:
        APP_NAME: analitica
    env_file:
      - ./Backend/.env
    ports:
      - "3003:3003"
    depends_on:
      - db

volumes:
  db_data:
#  frontend:
#    build:
#      context: ./Frontend/front-gestionti
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    depends_on:
#      - pagos
#      - conciliacion
#      - analitica