services:
  pagos:
    build:
      context: ./Backend
      dockerfile: Dockerfile
      args:
        APP_NAME: pagos
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  conciliacion:
    build:
      context: ./Backend
      dockerfile: Dockerfile
      args:
        APP_NAME: conciliacion
    ports:
      - "3002:3002"
    environment:
      - PORT=3002

  analitica:
    build:
      context: ./Backend
      dockerfile: Dockerfile
      args:
        APP_NAME: analitica
    ports:
      - "3003:3003"
    environment:
      - PORT=3003

  frontend:
    build:
      context: ./Frontend/front-gestionti
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - pagos
      - conciliacion
      - analitica